//
//  MediasWorker.swift
//  FinancialHouse
//
//  Created by Olgu on 17.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediasStoreProtocol {
    func fetchMedias(request: Medias.FetchMedias.Request,
                     completionHandler: @escaping ([ItunesItem]?, ItunesNetworkError?) -> Void)
    func deleteMedia(request: Medias.DeleteMedia.Request,
                     completionHandler: @escaping (ItunesItem?, IndexPath?, [ItunesItem]?, ItunesNetworkError?) -> Void)
}

final class MediasWorker {
    var ordersStore: MediasStoreProtocol
    
    init(ordersStore: MediasStoreProtocol) {
        self.ordersStore = ordersStore
    }
    
    func fetchMedias(request: Medias.FetchMedias.Request,
                     completionHandler: @escaping ([ItunesItem]?, ItunesNetworkError?) -> Void) {
        
        ordersStore.fetchMedias(request: request) { (itunesMainData, error) in
            DispatchQueue.main.async {
                
                if let error = error {
                    completionHandler(nil, error)
                    return
                }
                
                completionHandler(itunesMainData, nil)
            }
        }
    }
    
    func deleteMedia(request: Medias.DeleteMedia.Request, completionHandler: @escaping (ItunesItem?, IndexPath?, [ItunesItem]?, ItunesNetworkError?) -> Void) {
        ordersStore.deleteMedia(request: request, completionHandler: completionHandler)
    }
    
}

