//
//  MediasRouter.swift
//  FinancialHouse
//
//  Created by Olgu on 17.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MediasRoutingLogic {
    func routeToMediaDetail()
}

protocol MediasDataPassing {
    var dataStore: MediasDataStore? { get }
}

final class MediasRouter: NSObject, MediasRoutingLogic, MediasDataPassing {
    
    weak var viewController: MediasViewController?
    var dataStore: MediasDataStore?
    
    // MARK: Routing
    
    func routeToMediaDetail() {
        let storyboard = UIStoryboard(name: "MediaDetail", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(ofType: MediaDetailViewController.self)
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: MediasViewController, destination: MediaDetailViewController){
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: MediasDataStore, destination: inout MediaDetailDataStore) {
        destination.item = source.selectedItem
    }
}
