//
//  MediasPresenter.swift
//  FinancialHouse
//
//  Created by Olgu on 17.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediasPresentationLogic {
    func presentSomething(response: Medias.Something.Response)
}

class MediasPresenter: MediasPresentationLogic {
    
    weak var viewController: MediasDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Medias.Something.Response) {
        let viewModel = Medias.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
