//
//  MediasModels.swift
//  FinancialHouse
//
//  Created by Olgu on 17.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Medias {
    // MARK: Use cases
    
    enum FetchMedias {
        enum MediaType: String {
            case podcast
            case movie
            case music
            case all
        }
        
        struct Request {
            var term: String
            var media: MediaType = .all
            var limit: Int = 100
        }
        
        struct Response {
            var items: [ItunesItem]?
        }
        
        struct ViewModel {
            struct DisplayedMedia: Identifiable {
                var id: String
                var mediaArtworkUrl: String
                var mediaName: String
            }
            
            var displayedMedias: [DisplayedMedia]
        }
    }
}
