//
//  MediasInteractor.swift
//  FinancialHouse
//
//  Created by Olgu on 17.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediasBusinessLogic {
    func doSomething(request: Medias.Something.Request)
}

protocol MediasDataStore {
    //var name: String { get set }
}

class MediasInteractor: MediasBusinessLogic, MediasDataStore {
    var presenter: MediasPresentationLogic?
    var worker: MediasWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Medias.Something.Request) {
        worker = MediasWorker()
        worker?.doSomeWork()
        
        let response = Medias.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
