//
//  MediaDetailInteractor.swift
//  FinancialHouse
//
//  Created by Olgu on 18.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediaDetailBusinessLogic {
    func getItem(request: MediaDetail.ShowMedia.Request)
}

protocol MediaDetailDataStore {
    var item: ItunesItem? { get set }
}

class MediaDetailInteractor: MediaDetailBusinessLogic, MediaDetailDataStore {
    var presenter: MediaDetailPresentationLogic?
    var worker: MediaDetailWorker?
    var item: ItunesItem?
    
    // MARK: Do something
    
    func getItem(request: MediaDetail.ShowMedia.Request) {
        let response = MediaDetail.ShowMedia.Response(item: item)
        presenter?.presentMediaDetail(response: response)
    }
}
