//
//  MediaDetailPresenter.swift
//  FinancialHouse
//
//  Created by Olgu on 18.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediaDetailPresentationLogic {
    func presentMediaDetail(response: MediaDetail.ShowMedia.Response)
}

class MediaDetailPresenter: MediaDetailPresentationLogic {
    
    weak var viewController: MediaDetailDisplayLogic?
    
    // MARK: Present Media Detail
    
    func presentMediaDetail(response: MediaDetail.ShowMedia.Response) {
        guard let item = response.item else { return }
        
        let displayedMedia = MediaDetail.ShowMedia.ViewModel.DisplayedMedia(
            id: "\(item.artistId ?? 0)",
            mediaArtworkUrl: item.artworkUrl600 ?? "",
            mediaName: item.artistName ?? "")
        
        let viewModel = MediaDetail.ShowMedia.ViewModel(displayedMedia: displayedMedia)
        viewController?.displayMedia(viewModel: viewModel)
    }
}
