//
//  MediaDetailModels.swift
//  FinancialHouse
//
//  Created by Olgu on 18.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MediaDetail {
    // MARK: Use cases
    
    enum ShowMedia {
        struct Request {
        }
        struct Response {
            var item: ItunesItem?
        }
        struct ViewModel {
            struct DisplayedMedia: Identifiable {
                var id: String
                var mediaArtworkUrl: String
                var mediaName: String
            }
            
            var displayedMedia: DisplayedMedia
        }
    }
}
